//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have not entered any number. \n Press enter to continue..
        /// </summary>
        internal static string ArgNullExc {
            get {
                return ResourceManager.GetString("ArgNullExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array sort..
        /// </summary>
        internal static string ArraySort {
            get {
                return ResourceManager.GetString("ArraySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not sorted array:.
        /// </summary>
        internal static string ArraySortNotSorted {
            get {
                return ResourceManager.GetString("ArraySortNotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorted array:.
        /// </summary>
        internal static string ArraySortSorted {
            get {
                return ResourceManager.GetString("ArraySortSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array values:.
        /// </summary>
        internal static string ArrayValues {
            get {
                return ResourceManager.GetString("ArrayValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average word length. .
        /// </summary>
        internal static string AverageWordLength {
            get {
                return ResourceManager.GetString("AverageWordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter string you want to be calculated..
        /// </summary>
        internal static string AverageWordLengthInput {
            get {
                return ResourceManager.GetString("AverageWordLengthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BYE!!.
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose one of following methods to invoke it..
        /// </summary>
        internal static string ChooseMethod {
            get {
                return ResourceManager.GetString("ChooseMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Would you like to try again? Press &apos;y&apos; on your keyboard if you do otherwise any other key..
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum of numbers devided by 3 or 5..
        /// </summary>
        internal static string DividedNumbersSum {
            get {
                return ResourceManager.GetString("DividedNumbersSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double letter..
        /// </summary>
        internal static string DoubleLetter {
            get {
                return ResourceManager.GetString("DoubleLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter first string..
        /// </summary>
        internal static string DoubleLetter1st {
            get {
                return ResourceManager.GetString("DoubleLetter1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter second string.
        /// </summary>
        internal static string DoubleLetter2nd {
            get {
                return ResourceManager.GetString("DoubleLetter2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect input format (expected number). Press enter to continue. .
        /// </summary>
        internal static string FormatExc {
            get {
                return ResourceManager.GetString("FormatExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Picture of a few pyramids. .
        /// </summary>
        internal static string ManyPyramidPicture {
            get {
                return ResourceManager.GetString("ManyPyramidPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter number of rows..
        /// </summary>
        internal static string ManyPyramidPictureInput {
            get {
                return ResourceManager.GetString("ManyPyramidPictureInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum of positive numbers in array..
        /// </summary>
        internal static string PosNumbersSum {
            get {
                return ResourceManager.GetString("PosNumbersSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pyramid picture..
        /// </summary>
        internal static string PyramidPicture {
            get {
                return ResourceManager.GetString("PyramidPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter number of the pyramid height..
        /// </summary>
        internal static string PyramidPictureInput {
            get {
                return ResourceManager.GetString("PyramidPictureInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replacing positive number in array on Zero. .
        /// </summary>
        internal static string ReplacingOnZero {
            get {
                return ResourceManager.GetString("ReplacingOnZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array values after replacing..
        /// </summary>
        internal static string ReplacingOnZeroAfter {
            get {
                return ResourceManager.GetString("ReplacingOnZeroAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the height of the triangle (integer number)..
        /// </summary>
        internal static string RightTriangeInput {
            get {
                return ResourceManager.GetString("RightTriangeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right triangle picture..
        /// </summary>
        internal static string RightTriangle {
            get {
                return ResourceManager.GetString("RightTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangle square..
        /// </summary>
        internal static string SquareCalc {
            get {
                return ResourceManager.GetString("SquareCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have entered not enough number of values. Press enter to continue..
        /// </summary>
        internal static string SquareCalcArgNullExc {
            get {
                return ResourceManager.GetString("SquareCalcArgNullExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter side value of rectangle through space..
        /// </summary>
        internal static string SquareCalcInput {
            get {
                return ResourceManager.GetString("SquareCalcInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Side values of rectangle must be greater than 0. press enter to continue..
        /// </summary>
        internal static string SquareCalcSideValuesUnder0 {
            get {
                return ResourceManager.GetString("SquareCalcSideValuesUnder0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum of even array elements..
        /// </summary>
        internal static string SumOfEvenElement {
            get {
                return ResourceManager.GetString("SumOfEvenElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Values of double array..
        /// </summary>
        internal static string SumOfEvenElementDoubleArray {
            get {
                return ResourceManager.GetString("SumOfEvenElementDoubleArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To exit method press 9 on keyboard . .
        /// </summary>
        internal static string TextDecoratinToExit {
            get {
                return ResourceManager.GetString("TextDecoratinToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text decoration..
        /// </summary>
        internal static string TextDecoration {
            get {
                return ResourceManager.GetString("TextDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text options:.
        /// </summary>
        internal static string TextDecorationOptions {
            get {
                return ResourceManager.GetString("TextDecorationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key to exit method..
        /// </summary>
        internal static string ToExit {
            get {
                return ResourceManager.GetString("ToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello! I wanna suggest you to have fun with some methods I made..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
